### ISSUE TITLE
The script causes visible layout issues when loading

### ISSUE THREAD

**Issue by makew0rld** [electerious/ackee-tracker#12] opened 2020-05-23 19:26 UTC
The Firefox console notifies me that:
```
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.
```
It also says that the problem is at `1:15966`, aka the 15,966th character in the script.

It is correct, as I was able to see repainting occur, where the style loaded once incorrectly, and then was corrected. This doesn't happen when I remove the script, but occurs no matter where I place it, at the bottom, at the top, without `async`, with `defer`, etc.

**Comment by electerious** [comment] 2020-05-24 19:11
You can take a closer look [at the source](https://github.com/electerious/ackee-tracker/blob/master/src/scripts/main.js), but I'm not aware of something that could trigger a layout change. It doesn't occur on my sites.

Let me know if you find out more.

**Comment by makew0rld** [comment] 2020-05-24 19:29
My site is https://www.makeworld.gq/ or [here](https://github.com/makeworld-the-better-one/makeworld-the-better-one.github.io) on Github. When I remove the script their are no more loading issues. Can you confirm this with my site?

**Comment by electerious** [comment] 2020-05-26 12:10
It's caused by a function called `isScrollable`. This function isn't part of Ackee.

**Comment by makew0rld** [comment] 2020-05-26 13:34
Thanks so much for looking at it. Where is that function in my website?

**Comment by makew0rld** [comment] 2020-05-26 15:58
Because I don't see how `isScrollable` could come up anywhere.

**Comment by Pomax** [comment] 2020-09-13 19:55
You can "prettify" sources, so you can actually see normal code:

![image](https://user-images.githubusercontent.com/177243/93027179-17338600-f5c0-11ea-876a-3ebd4a8adfdf.png)

clicking that, we can now see that this _is_ actually ackee, because of this line:

```
browserWidth:
            document.documentElement.clientWidth || window.outerWidth,
```

Asking the browser for `clientWidth` _forces_ the browser to evaluate the DOM, even if it wasn't ready to do that yet, hence the "Layout was forced before the page was fully loaded" error.

**Comment by makew0rld** [comment] 2020-09-13 20:27
@Pomax Aha! Thanks for figuring this out. @electerious Can you update the script to not require this? Seems like you can just use `window.outerWidth` maybe?

**Comment by electerious** [comment] 2020-09-14 07:07
Good to know. We can switch to `window.outerWidth` and `window.outerHeight` as we're talking from the browser width/height anyway. `document.documentElement.clientWidth` is the width of the website area (without the browser toolbar, sidebar and other panels).

PR welcome!

**Comment by electerious** [comment] 2020-09-27 10:03
I've adjusted the script. The issue will be fixed in the next release of `ackee-tracker`.

**Closed as completed by electerious** 2020-09-27 10:03 UTC
Labels: help wanted
